# Generated by Django 5.2.1 on 2025-05-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CyptographyTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('Plaintext', models.CharField(max_length=1000)),
                ('Ciphertext', models.CharField(max_length=1000)),
            ],
        ),
    ]
