# Generated by Django 5.2.1 on 2025-05-26 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cyptographytool',
            name='key',
            field=models.IntegerField(default=0),
        ),
    ]
